import { Product, Review } from '@/types/product';
import { getSmartPhoto, vietnamPhotos, golfPhotos, hotelPhotos, spaPhotos, foodPhotos, vehiclePhotos, guidePhotos, optimizeUnsplash } from './unsplash';

// 상품 정보로 가장 적합한 이미지 URL 생성
const img = (title: string, location: string, category: string, w = 800) =>
  getSmartPhoto({ title, location, category, width: w });

// ─── 최신 상품 (4개) ──────────────────────────────────────────────────
export const mockRecentProducts: Product[] = [
  {
    id: '1',
    title: '푸꾸옥 관광 및 휴양',
    location: '푸꾸옥',
    country: '베트남',
    duration: '3박 5일',
    price: 630000,
    imageUrl: img('푸꾸옥 관광 및 휴양', '푸꾸옥', 'tour'),
    category: 'tour',
  },
  {
    id: '2',
    title: '다낭 프리미엄 리조트',
    location: '다낭',
    country: '베트남',
    duration: '4박 6일',
    price: 890000,
    imageUrl: img('다낭 프리미엄 리조트', '다낭', 'hotel'),
    category: 'hotel',
  },
  {
    id: '3',
    title: '하노이 문화 투어',
    location: '하노이',
    country: '베트남',
    duration: '3박 4일',
    price: 550000,
    imageUrl: img('하노이 문화 투어', '하노이', 'tour'),
    category: 'tour',
  },
  {
    id: '4',
    title: '나트랑 해변 휴양',
    location: '나트랑',
    country: '베트남',
    duration: '3박 5일',
    price: 720000,
    imageUrl: img('나트랑 해변 휴양', '나트랑', 'tour'),
    category: 'tour',
  },
];

// ─── 할인 상품 (3개) ──────────────────────────────────────────────────
export const mockDiscountedProducts: Product[] = [
  {
    id: '5',
    title: '푸꾸옥 리조트 특가',
    location: '푸꾸옥',
    country: '베트남',
    duration: '3박 4일',
    price: 630000,
    originalPrice: 850000,
    rating: 4.0,
    // 호텔 카테고리처럼 수상 리조트 이미지
    imageUrl: optimizeUnsplash(hotelPhotos.overwater),
    category: 'hotel',
  },
  {
    id: '6',
    title: '다낭 럭셔리 패키지',
    location: '다낭',
    country: '베트남',
    duration: '4박 5일',
    price: 980000,
    originalPrice: 1200000,
    rating: 4.5,
    // 비치프론트 인피니티 풀
    imageUrl: optimizeUnsplash(hotelPhotos.beachfront),
    category: 'hotel',
  },
  {
    id: '7',
    title: '호치민 시티 특가',
    location: '호치민',
    country: '베트남',
    duration: '2박 4일',
    price: 450000,
    originalPrice: 600000,
    rating: 4.2,
    imageUrl: img('호치민 시티 특가', '호치민', 'tour'),
    category: 'tour',
  },
];

// ─── BEST 골프 (5개 — 각기 다른 코스 이미지) ──────────────────────────
export const mockBestGolfProducts: Product[] = [
  {
    id: '8',
    title: '푸꾸옥 골프 & 해양 리조트',
    location: '푸꾸옥',
    country: '베트남',
    duration: '3박 5일',
    price: 1200000,
    rating: 4.8,
    // 열대 해안 골프장 (tropical)
    imageUrl: optimizeUnsplash(golfPhotos.tropical),
    category: 'golf',
  },
  {
    id: '9',
    title: '다낭 오션뷰 골프 리조트',
    location: '다낭',
    country: '베트남',
    duration: '4박 6일',
    price: 1500000,
    rating: 4.9,
    // 해안 절경 골프장 (coastal)
    imageUrl: optimizeUnsplash(golfPhotos.coastal),
    category: 'golf',
  },
  {
    id: '10',
    title: '하노이 왕실 골프 투어',
    location: '하노이',
    country: '베트남',
    duration: '3박 4일',
    price: 1100000,
    rating: 4.7,
    // 녹음 가득한 코스 (green)
    imageUrl: optimizeUnsplash(golfPhotos.green),
    category: 'golf',
  },
  {
    id: '11',
    title: '나트랑 씨사이드 골프 패키지',
    location: '나트랑',
    country: '베트남',
    duration: '3박 5일',
    price: 1350000,
    rating: 4.6,
    // 링크스 스타일 해변 코스 (links)
    imageUrl: optimizeUnsplash(golfPhotos.links),
    category: 'golf',
  },
  {
    id: '12',
    title: '달랏 힐링 고원 골프',
    location: '달랏',
    country: '베트남',
    duration: '2박 4일',
    price: 1000000,
    rating: 4.5,
    // 고원 리조트 코스 (highland)
    imageUrl: optimizeUnsplash(golfPhotos.highland),
    category: 'golf',
  },
];

// ─── BEST 투어 (5개) ──────────────────────────────────────────────────
export const mockBestTourProducts: Product[] = [
  {
    id: '13',
    title: '푸꾸옥 아일랜드 투어',
    location: '푸꾸옥',
    country: '베트남',
    duration: '3박 5일',
    price: 780000,
    rating: 4.7,
    imageUrl: img('푸꾸옥 아일랜드 투어', '푸꾸옥', 'tour'),
    category: 'tour',
  },
  {
    id: '14',
    title: '하롱베이 럭셔리 크루즈',
    location: '하롱베이',
    country: '베트남',
    duration: '2박 3일',
    price: 650000,
    rating: 4.8,
    imageUrl: img('하롱베이 럭셔리 크루즈', '하롱베이', 'tour'),
    category: 'tour',
  },
  {
    id: '15',
    title: '메콩델타 투어',
    location: '메콩델타',
    country: '베트남',
    duration: '1박 2일',
    price: 350000,
    rating: 4.6,
    imageUrl: img('메콩델타 투어', '메콩델타', 'tour'),
    category: 'tour',
  },
  {
    id: '16',
    title: '호이안 올드타운 야간 투어',
    location: '호이안',
    country: '베트남',
    duration: '2박 3일',
    price: 480000,
    rating: 4.9,
    imageUrl: img('호이안 올드타운 야간 투어', '호이안', 'tour'),
    category: 'tour',
  },
  {
    id: '17',
    title: '하노이 시티 & 문화 투어',
    location: '하노이',
    country: '베트남',
    duration: '1박 2일',
    price: 290000,
    rating: 4.5,
    imageUrl: img('하노이 시티 & 문화 투어', '하노이', 'tour'),
    category: 'tour',
  },
];

// ─── BEST 스파 (6개) ──────────────────────────────────────────────────
export const mockSpaProducts: Product[] = [
  {
    id: '18',
    title: '다낭 럭셔리 스파 & 마사지 패키지',
    location: '다낭',
    country: '베트남',
    duration: '3시간',
    price: 89000,
    originalPrice: 120000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(spaPhotos.massage),
    category: 'spa',
  },
  {
    id: '19',
    title: '나트랑 진흙 온천 스파',
    location: '나트랑',
    country: '베트남',
    duration: '4시간',
    price: 75000,
    originalPrice: 100000,
    rating: 4.8,
    imageUrl: optimizeUnsplash(spaPhotos.pool),
    category: 'spa',
  },
  {
    id: '20',
    title: '호이안 허브 아로마 테라피',
    location: '호이안',
    country: '베트남',
    duration: '2시간',
    price: 65000,
    rating: 4.7,
    imageUrl: optimizeUnsplash(spaPhotos.stone),
    category: 'spa',
  },
  {
    id: '21',
    title: '하노이 전통 베트남 마사지',
    location: '하노이',
    country: '베트남',
    duration: '90분',
    price: 55000,
    rating: 4.6,
    imageUrl: optimizeUnsplash(spaPhotos.massage),
    category: 'spa',
  },
  {
    id: '22',
    title: '호치민 5성급 호텔 스파',
    location: '호치민',
    country: '베트남',
    duration: '3시간',
    price: 120000,
    originalPrice: 160000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(spaPhotos.pool),
    category: 'spa',
  },
  {
    id: '23',
    title: '푸꾸옥 리조트 커플 스파',
    location: '푸꾸옥',
    country: '베트남',
    duration: '4시간',
    price: 180000,
    originalPrice: 240000,
    rating: 5.0,
    imageUrl: optimizeUnsplash(spaPhotos.stone),
    category: 'spa',
  },
];

// ─── 레스토랑/음식 투어 (6개) ─────────────────────────────────────────
export const mockRestaurantProducts: Product[] = [
  {
    id: '24',
    title: '하노이 퍼 & 번미 로컬 맛집 투어',
    location: '하노이',
    country: '베트남',
    duration: '4시간',
    price: 58000,
    rating: 4.8,
    imageUrl: optimizeUnsplash(foodPhotos.pho),
    category: 'restaurant',
  },
  {
    id: '25',
    title: '다낭 해산물 디너 프리미엄 코스',
    location: '다낭',
    country: '베트남',
    duration: '2시간',
    price: 95000,
    originalPrice: 130000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(foodPhotos.seafood),
    category: 'restaurant',
  },
  {
    id: '26',
    title: '호이안 야시장 스트리트 푸드 투어',
    location: '호이안',
    country: '베트남',
    duration: '3시간',
    price: 48000,
    rating: 4.7,
    imageUrl: optimizeUnsplash(foodPhotos.market),
    category: 'restaurant',
  },
  {
    id: '27',
    title: '호치민 메콩델타 쿠킹 클래스',
    location: '호치민',
    country: '베트남',
    duration: '5시간',
    price: 85000,
    rating: 4.8,
    imageUrl: optimizeUnsplash(foodPhotos.street),
    category: 'restaurant',
  },
  {
    id: '28',
    title: '나트랑 해변 BBQ & 씨푸드 뷔페',
    location: '나트랑',
    country: '베트남',
    duration: '3시간',
    price: 78000,
    originalPrice: 100000,
    rating: 4.6,
    imageUrl: optimizeUnsplash(foodPhotos.seafood),
    category: 'restaurant',
  },
  {
    id: '29',
    title: '푸꾸옥 선셋 디너 크루즈',
    location: '푸꾸옥',
    country: '베트남',
    duration: '3시간',
    price: 120000,
    originalPrice: 150000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(foodPhotos.seafood),
    category: 'restaurant',
  },
];

// ─── 차량/이동 서비스 (6개) ──────────────────────────────────────────
export const mockVehicleProducts: Product[] = [
  {
    id: '30',
    title: '하노이 공항 픽업 & 드롭 서비스',
    location: '하노이',
    country: '베트남',
    duration: '편도',
    price: 35000,
    rating: 4.7,
    imageUrl: optimizeUnsplash(vehiclePhotos.van),
    category: 'vehicle',
  },
  {
    id: '31',
    title: '다낭 공항 ↔ 호텔 리무진 이동',
    location: '다낭',
    country: '베트남',
    duration: '편도',
    price: 45000,
    rating: 4.8,
    imageUrl: optimizeUnsplash(vehiclePhotos.limousine),
    category: 'vehicle',
  },
  {
    id: '32',
    title: '다낭 → 호이안 전용 차량 이동',
    location: '다낭',
    country: '베트남',
    duration: '1시간',
    price: 55000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(vehiclePhotos.limousine),
    category: 'vehicle',
  },
  {
    id: '33',
    title: '호치민 공항 픽업 & 시티투어 차량',
    location: '호치민',
    country: '베트남',
    duration: '8시간',
    price: 120000,
    originalPrice: 150000,
    rating: 4.8,
    imageUrl: optimizeUnsplash(vehiclePhotos.van),
    category: 'vehicle',
  },
  {
    id: '34',
    title: '나트랑 전일 전용 차량 (8인승)',
    location: '나트랑',
    country: '베트남',
    duration: '8시간',
    price: 150000,
    rating: 4.7,
    imageUrl: optimizeUnsplash(vehiclePhotos.bus),
    category: 'vehicle',
  },
  {
    id: '35',
    title: '푸꾸옥 공항 픽업 & 섬 투어 차량',
    location: '푸꾸옥',
    country: '베트남',
    duration: '1일',
    price: 90000,
    rating: 4.6,
    imageUrl: optimizeUnsplash(vehiclePhotos.van),
    category: 'vehicle',
  },
];

// ─── 가이드 서비스 (6개) ─────────────────────────────────────────────
export const mockGuideProducts: Product[] = [
  {
    id: '36',
    title: '하노이 한국어 전문 가이드 (1일)',
    location: '하노이',
    country: '베트남',
    duration: '8시간',
    price: 120000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(guidePhotos.cultural),
    category: 'guide',
  },
  {
    id: '37',
    title: '다낭·호이안 문화 투어 가이드',
    location: '다낭',
    country: '베트남',
    duration: '10시간',
    price: 145000,
    originalPrice: 180000,
    rating: 4.8,
    imageUrl: optimizeUnsplash(guidePhotos.group),
    category: 'guide',
  },
  {
    id: '38',
    title: '하롱베이 크루즈 전문 가이드',
    location: '하노이',
    country: '베트남',
    duration: '1박 2일',
    price: 200000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(guidePhotos.private),
    category: 'guide',
  },
  {
    id: '39',
    title: '호치민 역사·문화 프라이빗 가이드',
    location: '호치민',
    country: '베트남',
    duration: '6시간',
    price: 110000,
    rating: 4.7,
    imageUrl: optimizeUnsplash(guidePhotos.cultural),
    category: 'guide',
  },
  {
    id: '40',
    title: '나트랑 스노클링 투어 가이드',
    location: '나트랑',
    country: '베트남',
    duration: '6시간',
    price: 95000,
    rating: 4.8,
    imageUrl: optimizeUnsplash(guidePhotos.group),
    category: 'guide',
  },
  {
    id: '41',
    title: '푸꾸옥 아일랜드 호핑 가이드',
    location: '푸꾸옥',
    country: '베트남',
    duration: '8시간',
    price: 130000,
    originalPrice: 160000,
    rating: 4.9,
    imageUrl: optimizeUnsplash(guidePhotos.private),
    category: 'guide',
  },
];

// ─── 전체 상품 통합 ──────────────────────────────────────────────────
export const allMockProducts: Product[] = [
  ...mockRecentProducts,
  ...mockDiscountedProducts,
  ...mockBestGolfProducts,
  ...mockBestTourProducts,
  ...mockSpaProducts,
  ...mockRestaurantProducts,
  ...mockVehicleProducts,
  ...mockGuideProducts,
];

// ─── 리뷰 ─────────────────────────────────────────────────────────────
export const mockReviews: Review[] = [
  {
    id: '1',
    productId: '14',
    productTitle: '하롱베이 럭셔리 크루즈',
    rating: 5,
    comment: '하롱베이 크루즈 정말 최고였어요! 석양이 아름답고 가이드분도 친절하셨습니다. 다음에도 꼭 망고트래블로 예약할게요.',
    images: [optimizeUnsplash(vietnamPhotos.halong, 400)],
    userName: '김여행',
    isActive: true,
    created: '2024-01-15T00:00:00Z',
    updated: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    productId: '9',
    productTitle: '다낭 오션뷰 골프 리조트',
    rating: 5,
    comment: '다낭 골프 리조트 패키지 정말 만족스러웠습니다. 골프장 시설도 좋고 호텔도 럭셔리해서 완벽한 힐링 여행이었어요.',
    images: [optimizeUnsplash(golfPhotos.coastal, 400)],
    userName: '박골프',
    isActive: true,
    created: '2024-01-20T00:00:00Z',
    updated: '2024-01-20T00:00:00Z',
  },
  {
    id: '3',
    productId: '16',
    productTitle: '호이안 올드타운 야간 투어',
    rating: 5,
    comment: '호이안 올드타운이 정말 동화 같았어요! 등불 축제도 보고 현지 음식도 너무 맛있었습니다. 강력 추천!',
    images: [optimizeUnsplash(vietnamPhotos.hoian, 400)],
    userName: '이투어',
    isActive: true,
    created: '2024-01-22T00:00:00Z',
    updated: '2024-01-22T00:00:00Z',
  },
  {
    id: '4',
    productId: '13',
    productTitle: '푸꾸옥 아일랜드 투어',
    rating: 4,
    comment: '푸꾸옥 해변이 상상 이상으로 아름다웠습니다. 물이 너무 맑고 깨끗해서 스노클링도 즐겼어요.',
    images: [optimizeUnsplash(vietnamPhotos.phuquoc, 400)],
    userName: '최여행',
    isActive: true,
    created: '2024-01-25T00:00:00Z',
    updated: '2024-01-25T00:00:00Z',
  },
  {
    id: '5',
    productId: '4',
    productTitle: '나트랑 스파 힐링',
    rating: 5,
    comment: '나트랑 스파 패키지 너무 좋았어요. 베트남 전통 마사지는 정말 피로가 싹 풀리는 느낌이었습니다!',
    images: [optimizeUnsplash(spaPhotos.massage, 400)],
    userName: '정힐링',
    isActive: true,
    created: '2024-02-01T00:00:00Z',
    updated: '2024-02-01T00:00:00Z',
  },
];
