import type { Product, ProductDetail } from '@/types/product';

/** 상품 ID별 상세 정보 (예약 페이지용). 없으면 기본값으로 채움 */
const details: Record<string, Partial<ProductDetail>> = {
  '1': {
    departureDate: '2026-03-15',
    returnDate: '2026-03-19',
    departureInfo: '08:25 - 인천공항 (VN417)',
    returnInfo: '22:40 - 인천공항 (VN418)',
    priceAdult: 630000,
    priceChild: 520000,
    priceInfant: 0,
    bookedCount: 2,
    blockSeats: 10,
    minPassengers: 2,
    inquiryPhone: '1588-8899',
    included: [
      '왕복 항공권 (이코노미)',
      '호텔 숙박 3박 (조식 포함)',
      '전일정 전용 차량',
      '한국어 가이드',
      '일정표 내 식사',
      '여행자 보험',
    ],
    excluded: ['개인 경비', '일정표 외 식사', '선택관광'],
    cancelPolicy: '출발 30일 전: 전액 환불 / 20~30일 전: 10% / 10~20일 전: 20% / 10일 전~당일: 30%',
    itinerary: [
      { day: 1, title: '인천 → 푸꾸옥', description: '인천공항 출발, 푸꾸옥 도착 후 호텔 체크인, 자유시간.', meals: '기내식' },
      { day: 2, title: '푸꾸옥 북부 투어', description: '사오비치, 푸꾸옥 사파리, 진주양식장 견학.', meals: '조식, 중식, 석식' },
      { day: 3, title: '남부 해양 액티비티', description: '스노클링 또는 카약, 시장 탐방.', meals: '조식, 중식, 석식' },
      { day: 4, title: '자유일', description: '리조트 휴양 또는 선택관광.', meals: '조식' },
      { day: 5, title: '푸꾸옥 → 인천', description: '체크아웃 후 공항 이동, 인천 도착.', meals: '조식, 기내식' },
    ],
  },
  '2': {
    departureDate: '2026-03-20',
    returnDate: '2026-03-25',
    departureInfo: '09:15 - 인천공항 (OZ721)',
    returnInfo: '18:30 - 인천공항 (OZ722)',
    priceAdult: 890000,
    priceChild: 0,
    priceInfant: 0,
    bookedCount: 4,
    blockSeats: 8,
    minPassengers: 2,
    inquiryPhone: '1588-8899',
    included: ['왕복 항공권', '5성급 리조트 4박', '조식', '공항 픽업/드롭'],
    excluded: ['일정표 외 식사', 'SPA·레저'],
    cancelPolicy: '출발 14일 전: 전액 환불 / 7일 전: 50% / 7일 미만: 환불 불가',
    itinerary: [
      { day: 1, title: '인천 → 다낭', description: '다낭 도착, 리조트 체크인.', meals: '기내식' },
      { day: 2, title: '리조트 휴양', description: '인피니티 풀, 비치 휴식.', meals: '조식, 석식' },
      { day: 3, title: '바나힐 또는 호이안', description: '선택 관광 (현지 결제 가능).', meals: '조식' },
      { day: 4, title: '자유일', description: '스파, 골프 등 옵션.', meals: '조식, 석식' },
      { day: 5, title: '체크아웃', description: '다낭 공항 이동 후 출국.', meals: '조식, 기내식' },
      { day: 6, title: '인천 도착', description: '-', meals: '-' },
    ],
  },
  '3': {
    departureDate: '2026-03-10',
    returnDate: '2026-03-13',
    departureInfo: '07:50 - 인천공항 (VN271)',
    returnInfo: '21:10 - 인천공항 (VN270)',
    priceAdult: 550000,
    priceChild: 450000,
    priceInfant: 0,
    bookedCount: 5,
    blockSeats: 10,
    minPassengers: 4,
    inquiryPhone: '1588-8899',
    included: ['왕복 항공권', '호텔 2박', '전용 차량', '한국어 가이드', '일정표 내 식사'],
    excluded: ['개인 경비', '선택관광'],
    cancelPolicy: '출발 20일 전: 전액 / 10일 전: 20% / 이후: 30%',
    itinerary: [
      { day: 1, title: '인천 → 하노이', description: '하노이 도착, 호안끼엠 호수·구시가지.', meals: '기내식, 석식' },
      { day: 2, title: '하노이 문화 투어', description: '호치민 영묘, 문묘, 박물관.', meals: '조식, 중식, 석식' },
      { day: 3, title: '하롱베이 당일 또는 자유', description: '선택: 하롱베이 당일 크루즈.', meals: '조식' },
      { day: 4, title: '하노이 → 인천', description: '공항 이동, 출국.', meals: '조식, 기내식' },
    ],
  },
  '13': {
    departureDate: '2026-04-01',
    returnDate: '2026-04-05',
    departureInfo: '08:25 - 인천공항 (VN417)',
    returnInfo: '22:40 - 인천공항 (VN418)',
    priceAdult: 780000,
    priceChild: 650000,
    priceInfant: 0,
    bookedCount: 0,
    blockSeats: 6,
    minPassengers: 2,
    inquiryPhone: '1588-8899',
    included: ['왕복 항공권', '호텔 3박', '전용 차량', '가이드', '일정표 내 식사', '여행자 보험'],
    excluded: ['개인 경비', '선택관광'],
    cancelPolicy: '출발 30일 전: 전액 환불 / 10일 전: 20% / 이후: 30%',
    itinerary: [
      { day: 1, title: '인천 → 푸꾸옥', description: '도착 후 호텔 체크인, 자유시간.', meals: '기내식' },
      { day: 2, title: '북부 투어', description: '사오비치, 사파리 등.', meals: '조식, 중식, 석식' },
      { day: 3, title: '남부 해양·시장', description: '스노클링 또는 시장 탐방.', meals: '조식, 중식, 석식' },
      { day: 4, title: '자유일', description: '비치·리조트 휴양.', meals: '조식' },
      { day: 5, title: '푸꾸옥 → 인천', description: '체크아웃, 공항 이동, 출국.', meals: '조식, 기내식' },
    ],
  },
  '14': {
    departureDate: '2026-03-22',
    returnDate: '2026-03-24',
    departureInfo: '06:40 - 인천공항 (VN271)',
    returnInfo: '21:10 - 인천공항 (VN270)',
    priceAdult: 650000,
    priceChild: 520000,
    priceInfant: 0,
    bookedCount: 3,
    blockSeats: 8,
    minPassengers: 2,
    inquiryPhone: '1588-8899',
    included: ['왕복 항공권 (하노이 경유)', '하롱베이 1박 크루즈', '호텔 1박', '전용 차량', '가이드', '식사'],
    excluded: ['개인 경비', '선택관광'],
    cancelPolicy: '출발 14일 전: 전액 / 7일 전: 20% / 이후: 30%',
    itinerary: [
      { day: 1, title: '인천 → 하노이 → 하롱베이', description: '하노이 도착 후 하롱베이 이동, 크루즈 탑승.', meals: '기내식, 중식, 석식' },
      { day: 2, title: '하롱베이 크루즈', description: '동굴·카약·수영, 선실 휴식.', meals: '조식, 중식, 석식' },
      { day: 3, title: '하롱베이 → 하노이 → 인천', description: '하노이 공항 이동, 출국.', meals: '조식, 기내식' },
    ],
  },
  '8': {
    departureDate: '2026-04-10',
    returnDate: '2026-04-14',
    departureInfo: '08:25 - 인천공항 (VN417)',
    returnInfo: '22:40 - 인천공항 (VN418)',
    priceAdult: 1200000,
    priceChild: 0,
    priceInfant: 0,
    bookedCount: 1,
    blockSeats: 4,
    minPassengers: 2,
    inquiryPhone: '1588-8899',
    included: ['왕복 항공권', '리조트 3박', '골프 2라운드', '전용 차량', '조식'],
    excluded: ['캐디·카트 현지 결제', '일정표 외 식사'],
    cancelPolicy: '출발 21일 전: 전액 / 14일 전: 50% / 이후: 환불 불가',
    itinerary: [
      { day: 1, title: '인천 → 푸꾸옥', description: '도착, 리조트 체크인.', meals: '기내식' },
      { day: 2, title: '1라운드', description: '푸꾸옥 오션뷰 골프장.', meals: '조식, 중식' },
      { day: 3, title: '2라운드 또는 휴양', description: '동일 코스 또는 비치 휴식.', meals: '조식' },
      { day: 4, title: '자유일', description: '스파·비치 옵션.', meals: '조식' },
      { day: 5, title: '푸꾸옥 → 인천', description: '체크아웃, 출국.', meals: '조식, 기내식' },
    ],
  },
  '9': {
    departureDate: '2026-04-05',
    returnDate: '2026-04-10',
    departureInfo: '09:15 - 인천공항 (OZ721)',
    returnInfo: '18:30 - 인천공항 (OZ722)',
    priceAdult: 1500000,
    priceChild: 0,
    priceInfant: 0,
    bookedCount: 2,
    blockSeats: 4,
    minPassengers: 2,
    inquiryPhone: '1588-8899',
    included: ['왕복 항공권', '5성 리조트 4박', '골프 2라운드', '조식', '공항 픽업'],
    excluded: ['캐디·카트', '일정표 외 식사'],
    cancelPolicy: '출발 21일 전: 전액 / 14일 전: 50% / 이후: 환불 불가',
    itinerary: [
      { day: 1, title: '인천 → 다낭', description: '다낭 도착, 리조트 체크인.', meals: '기내식' },
      { day: 2, title: '1라운드', description: '다낭 오션뷰 골프장.', meals: '조식, 중식' },
      { day: 3, title: '휴양 또는 2라운드', description: '풀·비치 또는 추가 라운드.', meals: '조식' },
      { day: 4, title: '2라운드', description: '동일 또는 타 코스.', meals: '조식' },
      { day: 5, title: '자유일', description: '호이안 당일 등 옵션.', meals: '조식' },
      { day: 6, title: '다낭 → 인천', description: '체크아웃, 출국.', meals: '조식, 기내식' },
    ],
  },
};

/** 상품 ID로 상세 정보 반환. 없으면 기본값만 채워서 반환 */
export function getProductDetail(product: Product): ProductDetail {
  const d = details[product.id];
  const base: ProductDetail = {
    ...product,
    priceAdult: product.price,
    priceChild: 0,
    priceInfant: 0,
    bookedCount: 0,
    blockSeats: 10,
    minPassengers: 2,
    inquiryPhone: '1588-8899',
    included: ['왕복 항공권', '호텔 숙박', '전용 차량', '한국어 가이드', '일정표 내 식사', '여행자 보험'],
    excluded: ['개인 경비', '일정표 외 식사', '선택관광'],
    cancelPolicy: '출발 30일 전 전액 환불, 이후 약관 참조.',
    itinerary: [],
  };
  if (!d) return base;
  return {
    ...base,
    ...d,
    priceAdult: d.priceAdult ?? base.price,
    priceChild: d.priceChild ?? 0,
    priceInfant: d.priceInfant ?? 0,
    bookedCount: d.bookedCount ?? 0,
    blockSeats: d.blockSeats ?? 10,
    minPassengers: d.minPassengers ?? 2,
    inquiryPhone: d.inquiryPhone ?? '1588-8899',
    included: d.included ?? base.included,
    excluded: d.excluded ?? base.excluded,
    cancelPolicy: d.cancelPolicy ?? base.cancelPolicy,
    itinerary: d.itinerary ?? base.itinerary,
  };
}
